// FR-HOOK-0001-0009, NFR-0004 — bootstrap payload assembly
// GT-2, GT-3 — per-IDE entry shapes, prefix on lead, absent→skip

import { buildHookPayloadJson } from '../escaping/json-string.js';
import { wrapInPrintf } from '../escaping/shell.js';
import { buildCopilotBashEntry, buildCopilotPowershellEntry } from './copilot-lock.js';
import {
  BOOTSTRAP_PREFIX,
  BOOTSTRAP_MANIFEST_ORDER,
  CLAUDE_PLUGIN_ROOT_ENTRY,
  CODEX_PLUGIN_ROOT_COMMAND,
  COPILOT_PLUGIN_ROOT_BASH,
  COPILOT_PLUGIN_ROOT_POWERSHELL,
} from '../spec/bootstrap-manifest.js';
import { stripFrontmatter } from '../serialize/frontmatter.js';
import { applyFolderRewrites, buildRenamePairs } from '../plugin-processors/plugin-rewrite-references.js';
import type { FileProcessingFrame, GenError, PluginProcessingFrame } from '../types.js';

const MAX_ENTRY_CHARS = 10000; // NFR-0004

/**
 * Build a claude hook entry JSON object (compact, with spaces after : and ,).
 * GT-3.1: {"type": "command", "command": "...", "once": true}
 */
function buildClaudeEntry(command: string): string {
  return `{"type": "command", "command": ${JSON.stringify(command)}, "once": true}`;
}

/**
 * Build a codex hook entry JSON object.
 * GT-3.2: {"type": "command", "command": "...", "statusMessage": "Loading Rosetta bootstrap", "timeout": 30}
 */
function buildCodexEntry(command: string): string {
  return `{"type": "command", "command": ${JSON.stringify(command)}, "statusMessage": "Loading Rosetta bootstrap", "timeout": 30}`;
}

/**
 * Build a copilot hook entry JSON object.
 * GT-3.3: {"type": "command", "bash": "...", "powershell": "..."}
 */
function buildCopilotEntry(bash: string, powershell: string): string {
  return `{"type": "command", "bash": ${JSON.stringify(bash)}, "powershell": ${JSON.stringify(powershell)}}`;
}

/**
 * Assemble the bootstrap payload string for a given IDE target.
 * Returns the string to inject as {{{bootstrap_hooks_<ide>}}}.
 * Also returns any errors (e.g. size limit violations).
 */
export function assembleBootstrapPayload(
  p: PluginProcessingFrame,
): { payload: string; errors: GenError[] } {
  const { spec, frames } = p;
  const errors: GenError[] = [];
  const folderPairs = buildRenamePairs(frames, spec);

  if (spec.hookEntryShape === 'cursor') {
    // Cursor: no bootstrap payload (GT-0)
    return { payload: '', errors };
  }

  const entryStrings: string[] = [];
  let lockIndex = 0;

  // Process manifest entries (FR-HOOK-0001: absent→skip, NFR-0006: content-agnostic)
  for (const ref of BOOTSTRAP_MANIFEST_ORDER) {
    // Skip index entries unless includeIndexEntries is set (FR-HOOK-0004)
    if (ref.basename.startsWith('__') && !spec.includeIndexEntries) continue;

    // Find the document in frames
    let body: string | null = null;
    let isIndex = false;

    if (ref.basename === '__rules_index__') {
      body = findIndexBody(frames, spec, 'rules');
      isIndex = true;
    } else if (ref.basename === '__workflows_index__') {
      body = findIndexBody(frames, spec, 'workflows');
      isIndex = true;
    } else {
      body = findDocBody(frames, ref.basename);
    }

    if (body === null) {
      // Absent → skip (FR-HOOK-0001)
      continue;
    }

    // Apply prefix to lead document (FR-HOOK-0003)
    // For lead: strip exactly one leading newline (gray-matter adds one after frontmatter),
    // then prepend the prefix. For non-lead: use body as-is (preserving its leading \n).
    let additionalContext: string;
    if (ref.isLead) {
      const cleanBody = body.startsWith('\n') ? body.slice(1) : body;
      additionalContext = BOOTSTRAP_PREFIX + cleanBody;
    } else {
      additionalContext = body;
    }

    // Apply folder rewrites to payload (FR-HOOK-0008) — only for doc bodies, not INDEX bodies.
    // INDEX bodies already use final target paths (generated by pluginGenerateIndexes).
    // Doc bodies use source paths (e.g. "workflows/") that need target-specific renaming.
    const rewrittenContext = isIndex
      ? additionalContext
      : applyFolderRewrites(additionalContext, folderPairs);

    // Build the JSON payload
    const jsonPayload = buildHookPayloadJson(rewrittenContext);

    // Build the IDE-specific entry
    const entryStr = buildEntryForIde(
      spec.hookEntryShape,
      jsonPayload,
      lockIndex,
      spec.name,
      errors,
      ref.basename,
    );

    if (entryStr !== null) {
      entryStrings.push(entryStr);
      lockIndex++;
    }
  }

  // Append plugin-root entry (GT-3.4, FR-HOOK-0007) — always last, separate
  const pluginRootEntry = buildPluginRootEntry(spec.hookEntryShape, lockIndex, folderPairs);
  if (pluginRootEntry !== null) {
    entryStrings.push(pluginRootEntry);
  }

  const payload = entryStrings.join(', ');
  return { payload, errors };
}

function findDocBody(frames: FileProcessingFrame[], basename: string): string | null {
  // Look for frame with matching basename in rules/ folder
  const matchingFrame = frames.find((f) => {
    const name = f.target.split('/').pop() ?? '';
    const stem = name.replace(/\.[^.]+$/, '');
    return stem === basename && f.target_contents !== null && !f.isBinary;
  });

  if (!matchingFrame || matchingFrame.target_contents === null) return null;

  const content = matchingFrame.target_contents as string;
  return stripFrontmatter(content);
}

function findIndexBody(
  frames: FileProcessingFrame[],
  spec: PluginProcessingFrame['spec'],
  kind: 'rules' | 'workflows',
): string | null {
  // Find the INDEX.md for the given kind
  const indexCandidates = frames.filter((f) => {
    const fname = f.target.split('/').pop();
    if (fname !== 'INDEX.md') return false;
    if (f.target_contents === null || f.isBinary) return false;

    // Check content starts with the expected heading
    const content = f.target_contents as string;
    if (kind === 'rules') return content.startsWith('# Rosetta Rules Index');
    return content.startsWith('# Rosetta Workflows Index');
  });

  if (indexCandidates.length === 0) return null;
  return indexCandidates[0].target_contents as string;
}

function buildEntryForIde(
  shape: string,
  jsonPayload: string,
  lockIndex: number,
  targetName: string,
  errors: GenError[],
  basename: string,
): string | null {
  // NFR-0004: size check on the jsonPayload (the escaped additionalContext entry) —
  // NOT the outer IDE wrapper. The requirement reads "any single bootstrap context entry
  // exceeding 10000 characters after escaping"; the per-document escaped payload IS that entry.
  // Copilot wraps the same payload in bash+powershell; measuring the combined wrapper
  // would double-count and produce false positives on real inputs.
  if (jsonPayload.length > MAX_ENTRY_CHARS) {
    errors.push({
      target: targetName,
      file: basename,
      message: `Bootstrap entry exceeds ${MAX_ENTRY_CHARS} chars (${jsonPayload.length})`,
      kind: 'soft',
    });
  }

  switch (shape) {
    case 'claude': {
      const command = wrapInPrintf(jsonPayload);
      return buildClaudeEntry(command);
    }
    case 'codex': {
      const command = wrapInPrintf(jsonPayload);
      return buildCodexEntry(command);
    }
    case 'copilot': {
      const bash = buildCopilotBashEntry(lockIndex, jsonPayload);
      const powershell = buildCopilotPowershellEntry(lockIndex, jsonPayload);
      return buildCopilotEntry(bash, powershell);
    }
    default:
      return null;
  }
}

function buildPluginRootEntry(
  shape: string,
  lockIndex: number,
  folderPairs: Array<[string, string]>,
): string | null {
  switch (shape) {
    case 'claude': {
      return buildClaudeEntry(CLAUDE_PLUGIN_ROOT_ENTRY.command);
    }
    case 'codex': {
      return buildCodexEntry(CODEX_PLUGIN_ROOT_COMMAND);
    }
    case 'copilot': {
      const bash = applyFolderRewrites(COPILOT_PLUGIN_ROOT_BASH, folderPairs);
      const powershell = applyFolderRewrites(COPILOT_PLUGIN_ROOT_POWERSHELL, folderPairs);
      return buildCopilotEntry(bash, powershell);
    }
    default:
      return null;
  }
}
